<?php

/**
 * IronCart_Scan — concurrency-lock unit test for ScanRunConsumer.
 *
 * Covers the race-closing invariants documented on
 * IronCartLabs/IronCartM2#155:
 *
 *   - The lock-held path NEVER reaches `runScan()`. Two concurrent
 *     `process()` invocations against the same consumer collapse to a
 *     single `checkRegistry->runAll()` call — the second one
 *     re-publishes its message back to the topic and ACKs cleanly.
 *   - The happy path acquires AND releases the lock around `runScan()`.
 *   - An exception inside `runScan()` still releases the lock so a
 *     poison message cannot brick every subsequent tick.
 *
 * The lock manager + publisher are mocked so this test exercises the
 * decision logic without standing up the Magento DI graph. Lives under
 * Test/Unit/Model alongside ScanRunConsumer itself. The Magento-free
 * unit cell in `.github/workflows/ci.yml` restricts the testsuite to
 * `Test/Unit/Report/**`, so this file is exercised by developers
 * running `composer test` locally against a Magento sandbox (where
 * `bin/magento setup:di:compile` has populated `generated/code/` with
 * `ScanRunFactory` + `ScanFindingFactory`). The companion
 * `Test/Unit/Report/ConsumerLockNameShapeTest` covers the
 * Magento-free regression vector (LOCK_NAME drift between
 * Cron\DrainScanConsumer and Model\ScanRunConsumer) that DOES run on
 * every PR.
 *
 * @copyright Copyright (c) Ironcart (https://ironcart.dev)
 * @license   MIT
 */

declare(strict_types=1);

namespace IronCart\Scan\Test\Unit\Model;

use IronCart\Scan\Check\CheckRegistry;
use IronCart\Scan\Model\ResourceModel\ScanFinding as ScanFindingResource;
use IronCart\Scan\Model\ResourceModel\ScanRun as ScanRunResource;
use IronCart\Scan\Model\ScanFindingFactory;
use IronCart\Scan\Model\ScanRun;
use IronCart\Scan\Model\ScanRunConsumer;
use IronCart\Scan\Model\ScanRunFactory;
use IronCart\Scan\Model\ScanRunPublisher;
use IronCart\Scan\Report\FindingDetailFormatter;
use IronCart\Scan\Report\ReportBuilder;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ProductMetadataInterface;
use Magento\Framework\Event\ManagerInterface as EventManagerInterface;
use Magento\Framework\Lock\LockManagerInterface;
use Magento\Framework\MessageQueue\PublisherInterface;
use Magento\Framework\Model\Context;
use Magento\Framework\Model\ResourceModel\AbstractResource;
use Magento\Framework\Registry;
use Magento\Framework\Serialize\Serializer\Json;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use RuntimeException;

/**
 * @covers \IronCart\Scan\Model\ScanRunConsumer
 */
class ScanRunConsumerLockTest extends TestCase
{
    protected function setUp(): void
    {
        // ScanRunFactory + ScanFindingFactory are generated by
        // `bin/magento setup:di:compile`. Outside a Magento sandbox
        // (e.g. on a fresh `composer install` checkout) the generated
        // classes are not on the autoload path, in which case this
        // suite is irrelevant — its purpose is documenting the lock
        // contract for developers who run the full Magento test
        // stack locally.
        if (!class_exists(ScanRunFactory::class)) {
            self::markTestSkipped(
                'ScanRunFactory is generated by `bin/magento setup:di:compile`'
                . ' — skipping in environments without a compiled Magento DI graph.'
            );
        }
        if (!class_exists(ScanFindingFactory::class)) {
            self::markTestSkipped('ScanFindingFactory is generated by Magento DI compile.');
        }
    }

    /**
     * Two consumer processes ("first" and "second") see the lock as
     * acquired and held respectively. Only the first reaches the check
     * registry; the second republishes its byte-identical payload to
     * the topic and returns cleanly.
     */
    public function testLockHeldProcessRepublishesAndSkipsCheckRegistry(): void
    {
        $body = '{"scan_run_id":7,"triggered_by":"admin:1"}';

        $registry = $this->createMock(CheckRegistry::class);
        // The whole point of #155: if the lock is held, the second
        // process MUST NOT invoke the check registry. Doubling this
        // call is the race we are closing.
        $registry->expects(self::never())->method('runAll');

        $lockManager = $this->createMock(LockManagerInterface::class);
        $lockManager->expects(self::once())
            ->method('lock')
            ->with(ScanRunConsumer::LOCK_NAME, 0)
            ->willReturn(false);
        // No unlock when we never acquired the lock.
        $lockManager->expects(self::never())->method('unlock');

        $publisher = $this->createMock(PublisherInterface::class);
        // Republish: same topic, byte-identical body.
        $publisher->expects(self::once())
            ->method('publish')
            ->with(ScanRunPublisher::TOPIC, $body);

        $logger = $this->createMock(LoggerInterface::class);
        $logger->expects(self::once())
            ->method('info')
            ->with(
                self::stringContains('drain lock held'),
                self::callback(static function (array $ctx): bool {
                    return ($ctx['lock_name'] ?? null) === ScanRunConsumer::LOCK_NAME
                        && ($ctx['scan_run_id'] ?? null) === 7;
                })
            );

        $consumer = $this->buildConsumer(
            scanRunId: 7,
            registry: $registry,
            lockManager: $lockManager,
            publisher: $publisher,
            logger: $logger
        );

        $consumer->process($body);
    }

    public function testHappyPathAcquiresAndReleasesLockAroundRunScan(): void
    {
        $body = '{"scan_run_id":11,"triggered_by":"cli"}';

        $registry = $this->createMock(CheckRegistry::class);
        $registry->expects(self::once())->method('runAll')->willReturn([]);

        $lockManager = $this->createMock(LockManagerInterface::class);
        $lockManager->expects(self::once())
            ->method('lock')
            ->with(ScanRunConsumer::LOCK_NAME, 0)
            ->willReturn(true);
        $lockManager->expects(self::once())
            ->method('unlock')
            ->with(ScanRunConsumer::LOCK_NAME);

        $publisher = $this->createMock(PublisherInterface::class);
        // Happy path NEVER republishes — that would queue infinite work.
        $publisher->expects(self::never())->method('publish');

        $consumer = $this->buildConsumer(
            scanRunId: 11,
            registry: $registry,
            lockManager: $lockManager,
            publisher: $publisher,
            logger: $this->createMock(LoggerInterface::class)
        );

        $consumer->process($body);
    }

    public function testCheckRegistryFailureStillReleasesLock(): void
    {
        $body = '{"scan_run_id":13,"triggered_by":"cron"}';

        $registry = $this->createMock(CheckRegistry::class);
        $registry->method('runAll')
            ->willThrowException(new RuntimeException('check blew up'));

        $lockManager = $this->createMock(LockManagerInterface::class);
        $lockManager->method('lock')->willReturn(true);
        // The finally block must release the lock — otherwise a single
        // bad message would brick every subsequent tick forever.
        $lockManager->expects(self::once())
            ->method('unlock')
            ->with(ScanRunConsumer::LOCK_NAME);

        $consumer = $this->buildConsumer(
            scanRunId: 13,
            registry: $registry,
            lockManager: $lockManager,
            publisher: $this->createMock(PublisherInterface::class),
            logger: $this->createMock(LoggerInterface::class)
        );

        // Must NOT re-throw: the consumer's failure-mode contract
        // converts throwables from runScan() into a `failed` row.
        $consumer->process($body);
    }

    /**
     * Assemble a `ScanRunConsumer` with the supplied collaborators.
     * Resource model + factory are stubbed to hydrate a queued ScanRun
     * row with the given id so the lock decision branches reach their
     * decision point.
     */
    private function buildConsumer(
        int $scanRunId,
        CheckRegistry $registry,
        LockManagerInterface $lockManager,
        PublisherInterface $publisher,
        LoggerInterface $logger
    ): ScanRunConsumer {
        $scanRunResource = $this->buildScanRunResource($scanRunId);
        $scanRunFactory = $this->buildScanRunFactory();

        return new ScanRunConsumer(
            $scanRunFactory,
            $scanRunResource,
            $this->createMock(ScanFindingFactory::class),
            $this->createMock(ScanFindingResource::class),
            $registry,
            $this->createMock(ReportBuilder::class),
            $this->createMock(ProductMetadataInterface::class),
            $this->buildPassthroughJson(),
            $logger,
            $this->createMock(FindingDetailFormatter::class),
            $lockManager,
            $publisher
        );
    }

    private function buildScanRunFactory(): ScanRunFactory
    {
        // Returns a new ScanRun instance on each `create()` call. The
        // real Magento-generated factory does the same thing via
        // `ObjectManager::create` — we side-step that here.
        $factory = $this->createMock(ScanRunFactory::class);
        $factory->method('create')->willReturnCallback(
            fn (): ScanRun => $this->buildBlankScanRun()
        );
        return $factory;
    }

    /**
     * Resource-model mock that "loads" a queued row with the given id
     * into whatever ScanRun model the factory just minted.
     */
    private function buildScanRunResource(int $scanRunId): ScanRunResource
    {
        $resource = $this->createMock(ScanRunResource::class);
        $resource->method('load')->willReturnCallback(
            function ($model) use ($scanRunId, $resource) {
                /** @var ScanRun $model */
                $model->setId($scanRunId);
                $model->setStatus(ScanRun::STATUS_QUEUED);
                $model->setTriggeredBy('cli');
                return $resource;
            }
        );
        // The save() call from inside runScan() is allowed but
        // uninteresting to assert on for the lock-branch tests.
        return $resource;
    }

    /**
     * Minimal ScanRun instance constructed with mocked dependencies.
     * AbstractModel needs Context + Registry for its constructor; we
     * stub both via the standard PHPUnit machinery.
     */
    private function buildBlankScanRun(): ScanRun
    {
        $eventManager = $this->createMock(EventManagerInterface::class);
        $context = $this->getMockBuilder(Context::class)
            ->disableOriginalConstructor()
            ->getMock();
        $context->method('getEventDispatcher')->willReturn($eventManager);

        $registry = $this->getMockBuilder(Registry::class)
            ->disableOriginalConstructor()
            ->getMock();

        return new ScanRun($context, $registry);
    }

    /**
     * Pass-through JSON serializer fixture — `unserialize`/`serialize`
     * delegate to PHP's native json_* so the test exercises real wire
     * shapes without standing up a Magento DI graph for
     * {@see \Magento\Framework\Serialize\Serializer\Json}.
     */
    private function buildPassthroughJson(): Json
    {
        return new class () extends Json {
            public function __construct()
            {
                // Skip parent constructor — Json's constructor needs
                // an EncoderInterface we are not wiring here.
            }
            public function serialize($data): string
            {
                return json_encode($data, JSON_UNESCAPED_SLASHES);
            }
            public function unserialize($string)
            {
                return json_decode((string)$string, true);
            }
        };
    }
}
